### ISSUE TITLE
[Bug]: Error: At least one chain must be set before attempting to connect a wallet

### ISSUE THREAD

**Issue by sgehrman** [blocknative/web3-onboard#1196]
### Current Behavior

getting this on hot reload in a react app

Error: At least one chain must be set before attempting to connect a wallet

It works when I reload the page ok, just hot reload fails

### Expected Behavior

shouldn't happen

### Steps To Reproduce

use a react app and change code and save to hotreload

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Runtime

### Package Version

2.6.0

### Node Version

16

### What browsers are you seeing the problem on?

Chrome

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@sgehrman can you share your code base so we can reproduce?

**Comment by Adamj1232** [comment]
@sgehrman would also be good to note, if you are using within a react project we have a React Hooks package that would make your implementation and usage more simple - https://www.npmjs.com/package/@web3-onboard/react

**Comment by sgehrman** [comment]
I'm using the react hooks.  I'm also on NextJS if that matters.
Can't easily share the code.

**Comment by sgehrman** [comment]
on hot reload, chains is [], on a normal load it has chains

**Comment by sgehrman** [comment]
hot reload calls init again with the same params, but the result has [] for chains

export const init = (options) => {
    web3Onboard = Web3Onboard(options);

    web3Onboard.state.get().chains == [] second call on hot reload.

    return web3Onboard;

**Comment by sgehrman** [comment]
Looking at your code now, but it's so hipster and cool, I can't make any sense of it. 

dispatch, svelte, actions, rxjs?  Too much complexity. It's probably failing in there somewhere.  Why not write normal code that works rather than this hipster fad overly engineered code?

**Comment by sgehrman** [comment]
Also, I'm unable to step though your code in Chrome.  No idea why, it won't auto format and it's all one line.  Build you code so ti's normal code that is debuggable.

**Comment by sgehrman** [comment]
trying this:

export const setupOnboard = () => {
  // hack for hot reload
  const existing = web3Onboard?.state.get();
  if (existing && existing?.chains?.length > 0) {
    console.log('init bypassed');
    return;
  }

  init({ params... })
}

but that has a sideeffect:
![gnome-shell-screenshot-EPJ8P1](https://user-images.githubusercontent.com/287137/183021963-15260f92-af2e-4f05-90e4-cf761fc579c9.png)

MetaMask - RPC Error: The method "eth_selectAccounts" does not exist / is not available. {code: -32601, message: 'The method "eth_selectAccounts" does not exist / is not available.', data: {…}}

So, it almost works.  Let me know if that gives you a clue.

**Comment by taylorjdawson** [comment]
@sgehrman There's a lot here, let's focus this issue a little bit. To restate: The issue is with hot reloading and seeing the "At least one chain..." message? 
If that is the case I have seen this behaviour before however, it seems like with the latest versions of the packages it has been resolved. 
Can you try reproducing the issue using [this demo](https://stackblitz.com/edit/nextjs-mjcfct?file=README.md)?

**Comment by taylorjdawson** [comment]
As a side note: Let's make sure comments about the code are constructive. Comments like  "so hipster and cool" or "Build you code so it's normal code that is debuggable" are very vague. Let's practice good OSS etiquette and if you see where there could be an improvement please let us know but using more helpful comments, thank you!

**Comment by katspaugh** [comment]
We have the same problem in a Next.js/React app.
Onboard is initialized in a `useEffect` (because we load chain configs async).

**Comment by Dinuz** [comment]
@aaronbarnardsound this is not really solved, it is directly related with my comment in [https://github.com/blocknative/web3-onboard/issues/888](url)

I am using VUE and the hot reload (due to reactivity changes) is a big issue. I keep getting the same annoying popup and message:

<img width="353" alt="Screen Shot 2022-12-17 at 4 21 27 PM" src="https://user-images.githubusercontent.com/1139472/208266414-d5eefdc6-e7dc-4cf0-a35f-81ff67da724c.png">

<img width="1390" alt="Screen Shot 2022-12-17 at 4 21 37 PM" src="https://user-images.githubusercontent.com/1139472/208266418-429e4d1d-e2ea-4495-8e10-468009ee7aac.png">

What I should do to just remove this? I am trying to have persistence on refresh

**Comment by jamesmorgan** [comment]
Also seeing this issue

**Comment by Adamj1232** [comment]
We will take a look into this issue and reopen if necessary. We will update here regardless. Thanks for raising
